/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import modelo.Memoria;

/**
 *
 * @author ser
 */
public class vConfiguracion extends javax.swing.JFrame {
    DefaultTableModel tablaSegmento;
    DefaultTableModel tablaSegmentoV;
    String [][] data={};
    String [][] dataV={};
    String titulos[] = {"Segmento","Tamaño"};
    private int contSegmento=0,contSegmentoV=0,sumaSegmento=0,sumaSegmentoV=0;
    /**
     * Creates new form vConfiguracion
     */
    public vConfiguracion() {
        initComponents();
        tablaSegmento=new DefaultTableModel(data,titulos);
        tblSegmento.setModel(tablaSegmento);
        tablaSegmentoV=new DefaultTableModel(dataV,titulos);
        tblSegmentacionV.setModel(tablaSegmentoV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDisco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtMemoriaVirtual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxAlgoritmoP = new javax.swing.JComboBox<>();
        lblCuanto = new javax.swing.JLabel();
        txtCuanto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbxAlgoritmoM = new javax.swing.JComboBox<>();
        lblTPagina = new javax.swing.JLabel();
        txtTPagina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSegmento = new javax.swing.JTable();
        lblTPagina1 = new javax.swing.JLabel();
        txtTFija = new javax.swing.JTextField();
        lblTPagina2 = new javax.swing.JLabel();
        txtTSegmento = new javax.swing.JTextField();
        lblTPagina3 = new javax.swing.JLabel();
        txtTSegmento1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSegmentacionV = new javax.swing.JTable();
        btnAgregar1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Memoria");

        txtMemoria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMemoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemoria.setText("1024");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Disco");

        txtDisco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDisco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDisco.setText("1024");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Memoria Virtual");

        txtMemoriaVirtual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMemoriaVirtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemoriaVirtual.setText("512");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel16)
                        .addComponent(txtMemoria)
                        .addComponent(jLabel17)
                        .addComponent(txtDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addComponent(txtMemoriaVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtMemoriaVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmos de Procesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        cbxAlgoritmoP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxAlgoritmoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "RR", "Feedback", "HRRN", "Prioridad" }));
        cbxAlgoritmoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlgoritmoPActionPerformed(evt);
            }
        });

        lblCuanto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCuanto.setText("Cuanto");

        txtCuanto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCuanto.setText("1");
        txtCuanto.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxAlgoritmoP, 0, 247, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCuanto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCuanto)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxAlgoritmoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuanto)
                    .addComponent(txtCuanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmos de Memoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        cbxAlgoritmoM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbxAlgoritmoM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fija", "Dinámica", "Paginación", "Segmentación" }));

        lblTPagina.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTPagina.setText("Tamaño Frames");

        txtTPagina.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTPagina.setText("1");

        tblSegmento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Segmento", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSegmento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSegmentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSegmento);
        if (tblSegmento.getColumnModel().getColumnCount() > 0) {
            tblSegmento.getColumnModel().getColumn(0).setResizable(false);
            tblSegmento.getColumnModel().getColumn(1).setResizable(false);
        }

        lblTPagina1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTPagina1.setText("Tamaño Fija");

        txtTFija.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTFija.setText("1");

        lblTPagina2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTPagina2.setText("Tamaño Segmento M");

        txtTSegmento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTSegmento.setText("1");

        lblTPagina3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTPagina3.setText("Tamaño Segmento V");

        txtTSegmento1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTSegmento1.setText("1");

        tblSegmentacionV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Segmento", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSegmentacionV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSegmentacionVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSegmentacionV);
        if (tblSegmentacionV.getColumnModel().getColumnCount() > 0) {
            tblSegmentacionV.getColumnModel().getColumn(0).setResizable(false);
            tblSegmentacionV.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAgregar1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregar1.setText("Agregar");
        btnAgregar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblTPagina1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                            .addComponent(txtTFija, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cbxAlgoritmoM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblTPagina)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGuardar))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTPagina2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTPagina3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTSegmento1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbxAlgoritmoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTPagina2)
                                .addComponent(txtTSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTPagina))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTFija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTPagina1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnAgregar)
                                .addGap(16, 16, 16))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTPagina3)
                            .addComponent(txtTSegmento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar1)
                            .addComponent(btnGuardar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaSegmento = new ArrayList<>();
        int total=tablaSegmento.getRowCount();
        int suma=Integer.parseInt(txtMemoria.getText());
        for(int i = 0;i<total;i++){
            suma-=Integer.parseInt(tablaSegmento.getValueAt(i, 1).toString());
            listaSegmento.add(String.valueOf(tablaSegmento.getValueAt(i, 1).toString()));
        }
        if(suma>0){
             listaSegmento.add(String.valueOf(suma));
        }
        ArrayList<String> listaSegmentoV = new ArrayList<>();
        int totalV=tablaSegmentoV.getRowCount();
        int sumaV=Integer.parseInt(txtMemoriaVirtual.getText());
        for(int i = 0;i<totalV;i++){
            suma-=Integer.parseInt(tablaSegmentoV.getValueAt(i, 1).toString());
            listaSegmentoV.add(String.valueOf(tablaSegmentoV.getValueAt(i, 1).toString()));
        }
        if(sumaV>0){
             listaSegmentoV.add(String.valueOf(sumaV));
        }
        ArrayList<Memoria> memoria= new ArrayList();
        ArrayList AlgoritmoP= new ArrayList();
        ArrayList AlgoritmoM= new ArrayList();
        AlgoritmoP.add(cbxAlgoritmoP.getSelectedItem().toString());
        AlgoritmoP.add(txtCuanto.getText());
        AlgoritmoM.add(cbxAlgoritmoM.getSelectedItem().toString());
        AlgoritmoM.add(txtTPagina.getText());
        AlgoritmoM.add(txtTSegmento.getText());
        AlgoritmoM.add(txtTFija.getText());
        Memoria memory;
        memory = new Memoria("Memoria", txtMemoria.getText());
        memoria.add(memory);

        if(Integer.parseInt(txtDisco.getText())<=1024 && (Integer.parseInt(txtDisco.getText())>Integer.parseInt(txtMemoriaVirtual.getText()))){
            memory= new Memoria("Disco", txtDisco.getText());
            memoria.add(memory);

            memory= new Memoria("Virtual", txtMemoriaVirtual.getText());
            memoria.add(memory);
            vGestor ventana = new vGestor( AlgoritmoP, AlgoritmoM,memoria,listaSegmento,listaSegmentoV);
            ventana.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Tamaño de Disco duro supera los 1024kb o la memoria virtual supera el tamaño del disco duro");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxAlgoritmoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlgoritmoPActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,cbxAlgoritmoP.getSelectedItem().toString()); 
        if(cbxAlgoritmoP.getSelectedItem().toString().equals("RR") || cbxAlgoritmoP.getSelectedItem().toString().equals("Feedback")){
            txtCuanto.enable(true);
        }else{
            txtCuanto.enable(false);
        }
    }//GEN-LAST:event_cbxAlgoritmoPActionPerformed
    private void popotTable(){
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem menuItem = new JMenuItem("Eliminar");
        
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int eli=tblSegmento.getSelectedRow();
                System.out.println(eli);
                if(eli>=0){
                    sumaSegmento-=Integer.parseInt(tablaSegmento.getValueAt(eli, 1).toString());
                    tablaSegmento.removeRow(eli);
                }else{
                    
                }
            }
        });
        
        popup.add(menuItem);
        tblSegmento.setComponentPopupMenu(popup);
    }
    private void popotTableV(){
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem menuItem = new JMenuItem("Eliminar");
        
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int eli=tblSegmentacionV.getSelectedRow();
                System.out.println(eli);
                if(eli>=0){
                    sumaSegmentoV-=Integer.parseInt(tablaSegmentoV.getValueAt(eli, 1).toString());
                    tablaSegmentoV.removeRow(eli);
                }else{
                    
                }
            }
        });
        
        popup.add(menuItem);
        tblSegmentacionV.setComponentPopupMenu(popup);
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        sumaSegmento+=Integer.parseInt(txtTSegmento.getText());
        if(sumaSegmento<=Integer.parseInt(txtMemoria.getText())){
            String datos[]={String.valueOf(contSegmento),txtTSegmento.getText()};
            tablaSegmento.addRow(datos);
            contSegmento+=1;
        }
        else{
            sumaSegmento-=Integer.parseInt(txtTSegmento.getText());
            String datos[]={String.valueOf(contSegmento),String.valueOf(Integer.parseInt(txtMemoria.getText())-sumaSegmento)};
            tablaSegmento.addRow(datos);
            JOptionPane.showMessageDialog(null,"No se puede crear un segmento con ese tamaño");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblSegmentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSegmentoMouseClicked
        // TODO add your handling code here:
         popotTable();
    }//GEN-LAST:event_tblSegmentoMouseClicked

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        sumaSegmentoV+=Integer.parseInt(txtTSegmento1.getText());
        if(sumaSegmentoV<=Integer.parseInt(txtMemoriaVirtual.getText())){
            String datos[]={String.valueOf(contSegmentoV),txtTSegmento1.getText()};
            tablaSegmentoV.addRow(datos);
            contSegmentoV+=1;
        }
        else{
            sumaSegmentoV-=Integer.parseInt(txtTSegmento1.getText());
            String datos[]={String.valueOf(contSegmentoV),String.valueOf(Integer.parseInt(txtMemoriaVirtual.getText())-sumaSegmentoV)};
            tablaSegmentoV.addRow(datos);
            JOptionPane.showMessageDialog(null,"No se puede crear un segmento con ese tamaño");
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void tblSegmentacionVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSegmentacionVMouseClicked
        // TODO add your handling code here:
        popotTableV();
    }//GEN-LAST:event_tblSegmentacionVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxAlgoritmoM;
    private javax.swing.JComboBox<String> cbxAlgoritmoP;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCuanto;
    private javax.swing.JLabel lblTPagina;
    private javax.swing.JLabel lblTPagina1;
    private javax.swing.JLabel lblTPagina2;
    private javax.swing.JLabel lblTPagina3;
    private javax.swing.JTable tblSegmentacionV;
    private javax.swing.JTable tblSegmento;
    private javax.swing.JTextField txtCuanto;
    private javax.swing.JTextField txtDisco;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtMemoriaVirtual;
    private javax.swing.JTextField txtTFija;
    private javax.swing.JTextField txtTPagina;
    private javax.swing.JTextField txtTSegmento;
    private javax.swing.JTextField txtTSegmento1;
    // End of variables declaration//GEN-END:variables
}
