/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import modelo.Memoria;

/**
 *
 * @author ser
 */
public class vConfiguracion extends javax.swing.JFrame {
    DefaultTableModel tablaSegmento;
    String [][] data={};
    String titulos[] = {"Segmento","Tamaño"};
    private int contSegmento=0,sumaSegmento=0;
    /**
     * Creates new form vConfiguracion
     */
    public vConfiguracion() {
        initComponents();
        tablaSegmento=new DefaultTableModel(data,titulos);
        tblSegmento.setModel(tablaSegmento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtMemoria = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDisco = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtMemoriaVirtual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxAlgoritmoP = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        lblCuanto = new javax.swing.JLabel();
        txtCuanto = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbxAlgoritmoM = new javax.swing.JComboBox<>();
        lblTPagina = new javax.swing.JLabel();
        txtTPagina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSegmento = new javax.swing.JTable();
        lblTPagina1 = new javax.swing.JLabel();
        txtTFija = new javax.swing.JTextField();
        lblTPagina2 = new javax.swing.JLabel();
        txtTSegmento = new javax.swing.JTextField();
        lblTPagina3 = new javax.swing.JLabel();
        txtTSegmento1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSegmentacionM = new javax.swing.JTable();
        btnAgregar1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Memoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Memoria");

        txtMemoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemoria.setText("1024");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Disco");

        txtDisco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDisco.setText("1024");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Memoria Virtual");

        txtMemoriaVirtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemoriaVirtual.setText("512");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(txtMemoria)
                    .addComponent(jLabel17)
                    .addComponent(txtDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addComponent(txtMemoriaVirtual))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtMemoriaVirtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmos de Procesos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        cbxAlgoritmoP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxAlgoritmoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "RR", "Feedback", "HRRN", "Prioridad" }));
        cbxAlgoritmoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlgoritmoPActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblCuanto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCuanto.setText("Cuanto");

        txtCuanto.setText("1");
        txtCuanto.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxAlgoritmoP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCuanto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCuanto)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxAlgoritmoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuanto)
                    .addComponent(txtCuanto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmos de Memoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        cbxAlgoritmoM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxAlgoritmoM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fija", "Dinámica", "Paginación", "Segmentación" }));
        cbxAlgoritmoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlgoritmoMActionPerformed(evt);
            }
        });

        lblTPagina.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTPagina.setText("Tamaño Pagina");

        txtTPagina.setText("1");
        txtTPagina.setEnabled(false);

        tblSegmento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Segmento", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSegmento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSegmentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSegmento);
        if (tblSegmento.getColumnModel().getColumnCount() > 0) {
            tblSegmento.getColumnModel().getColumn(0).setResizable(false);
            tblSegmento.getColumnModel().getColumn(1).setResizable(false);
        }

        lblTPagina1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTPagina1.setText("Tamaño Fija");

        txtTFija.setText("1");
        txtTFija.setEnabled(false);

        lblTPagina2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTPagina2.setText("Tamaño Segmento M");

        txtTSegmento.setText("1");

        lblTPagina3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblTPagina3.setText("Tamaño Segmento V");

        txtTSegmento1.setText("1");

        tblSegmentacionM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Segmento", "Tamaño"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSegmentacionM);
        if (tblSegmentacionM.getColumnModel().getColumnCount() > 0) {
            tblSegmentacionM.getColumnModel().getColumn(0).setResizable(false);
            tblSegmentacionM.getColumnModel().getColumn(1).setResizable(false);
        }

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cbxAlgoritmoM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTPagina1)
                            .addComponent(lblTPagina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTPagina)
                            .addComponent(txtTFija, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTPagina2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(txtTSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTSegmento1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblTPagina3)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxAlgoritmoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTPagina)
                    .addComponent(txtTPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTPagina1)
                    .addComponent(txtTFija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTPagina2)
                    .addComponent(txtTSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtTSegmento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnAgregar))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(312, Short.MAX_VALUE)
                    .addComponent(lblTPagina3)
                    .addGap(163, 163, 163)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaSegmento = new ArrayList<>();
        int total=tablaSegmento.getRowCount();
        for(int i = 0;i<total;i++){
            listaSegmento.add(String.valueOf(tablaSegmento.getValueAt(i, 1).toString()));
        }
        ArrayList<Memoria> memoria= new ArrayList();
        ArrayList AlgoritmoP= new ArrayList();
        ArrayList AlgoritmoM= new ArrayList();
        AlgoritmoP.add(cbxAlgoritmoP.getSelectedItem().toString());
        AlgoritmoP.add(txtCuanto.getText());
        AlgoritmoM.add(cbxAlgoritmoM.getSelectedItem().toString());
        AlgoritmoM.add(txtTPagina.getText());
        AlgoritmoM.add(txtTSegmento.getText());
        AlgoritmoM.add(txtTFija.getText());
        Memoria memory;
        memory = new Memoria("Memoria", txtMemoria.getText());
        memoria.add(memory);

        if(Integer.parseInt(txtDisco.getText())<=1024 && (Integer.parseInt(txtDisco.getText())>Integer.parseInt(txtMemoriaVirtual.getText()))){
            memory= new Memoria("Disco", txtDisco.getText());
            memoria.add(memory);

            memory= new Memoria("Virtual", txtMemoriaVirtual.getText());
            memoria.add(memory);
            vGestor ventana = new vGestor( AlgoritmoP, AlgoritmoM,memoria,listaSegmento);
            ventana.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Tamaño de Disco duro supera los 1024kb o la memoria virtual supera el tamaño del disco duro");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxAlgoritmoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlgoritmoPActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,cbxAlgoritmoP.getSelectedItem().toString()); 
        if(cbxAlgoritmoP.getSelectedItem().toString().equals("RR") || cbxAlgoritmoP.getSelectedItem().toString().equals("Feedback")){
            txtCuanto.enable(true);
        }else{
            txtCuanto.enable(false);
        }
    }//GEN-LAST:event_cbxAlgoritmoPActionPerformed

    private void cbxAlgoritmoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlgoritmoMActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,cbxAlgoritmoM.getSelectedItem().toString());
        if(cbxAlgoritmoM.getSelectedItem().toString().equals("Segmentación")){
            btnAgregar.enable(true);
            txtTSegmento.enable(true);
            txtTPagina.enable(false);
            txtTFija.enable(false);
        }else if(cbxAlgoritmoM.getSelectedItem().toString().equals("Paginación")){
            btnAgregar.enable(false);
            txtTSegmento.enable(false);
            txtTPagina.enable(true);
            txtTFija.enable(false);
        }
        else if(cbxAlgoritmoM.getSelectedItem().toString().equals("Fija")){
            btnAgregar.enable(false);
            txtTSegmento.enable(false);
            txtTPagina.enable(false);
            txtTFija.enable(true);
        }
        else{
            btnAgregar.enable(false);
            txtTSegmento.enable(false);
            txtTPagina.enable(false);
            txtTFija.enable(false);
        }
    }//GEN-LAST:event_cbxAlgoritmoMActionPerformed
    private void popotTable(){
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem menuItem = new JMenuItem("Eliminar");
        
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int eli=tblSegmento.getSelectedRow();
                System.out.println(eli);
                if(eli>=0){
                    sumaSegmento-=Integer.parseInt(tablaSegmento.getValueAt(eli, 1).toString());
                    tablaSegmento.removeRow(eli);
                }else{
                    
                }
            }
        });
        
        popup.add(menuItem);
        tblSegmento.setComponentPopupMenu(popup);
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        sumaSegmento+=Integer.parseInt(txtTSegmento.getText());
        if(sumaSegmento<=Integer.parseInt(txtMemoria.getText())){
            String datos[]={String.valueOf(contSegmento),txtTSegmento.getText()};
            tablaSegmento.addRow(datos);
            contSegmento+=1;
        }
        else{
            sumaSegmento-=Integer.parseInt(txtTSegmento.getText());
            JOptionPane.showMessageDialog(null,"No se puede crear un segmento con ese tamaño");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblSegmentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSegmentoMouseClicked
        // TODO add your handling code here:
        System.out.println("entra");
         popotTable();
    }//GEN-LAST:event_tblSegmentoMouseClicked

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxAlgoritmoM;
    private javax.swing.JComboBox<String> cbxAlgoritmoP;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCuanto;
    private javax.swing.JLabel lblTPagina;
    private javax.swing.JLabel lblTPagina1;
    private javax.swing.JLabel lblTPagina2;
    private javax.swing.JLabel lblTPagina3;
    private javax.swing.JTable tblSegmentacionM;
    private javax.swing.JTable tblSegmento;
    private javax.swing.JTextField txtCuanto;
    private javax.swing.JTextField txtDisco;
    private javax.swing.JTextField txtMemoria;
    private javax.swing.JTextField txtMemoriaVirtual;
    private javax.swing.JTextField txtTFija;
    private javax.swing.JTextField txtTPagina;
    private javax.swing.JTextField txtTSegmento;
    private javax.swing.JTextField txtTSegmento1;
    // End of variables declaration//GEN-END:variables
}
